# Generated by Django 4.2.2 on 2025-02-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('REVENUE', 'Revenue Analysis'), ('OCCUPANCY', 'Occupancy Analysis'), ('PERFORMANCE', 'Performance Metrics'), ('BOOKING', 'Booking Trends')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('REVENUE_CHART', 'Revenue Chart'), ('OCCUPANCY_CHART', 'Occupancy Chart'), ('PERFORMANCE_METRICS', 'Performance Metrics'), ('BOOKING_TRENDS', 'Booking Trends')], max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
