# Generated by Django 4.2.2 on 2025-02-07 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_group_booking', models.BooleanField(default=False)),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('group_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seasonal_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('demand_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hours_before_checkin', models.PositiveIntegerField()),
                ('charge_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_size', models.PositiveIntegerField()),
                ('group_type', models.CharField(choices=[('CORPORATE', 'Corporate'), ('FAMILY', 'Family'), ('TOUR', 'Tour Group'), ('OTHER', 'Other')], max_length=50)),
                ('special_requests', models.TextField(blank=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_type', models.CharField(choices=[('FULL', 'Full Payment'), ('SPLIT', 'Split Payment'), ('DEPOSIT', 'Deposit Required')], default='FULL', max_length=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('initiated', 'Initiated'), ('failed', 'Failed'), ('refunding', 'Refunding'), ('refunded', 'Refunded'), ('unpaid', 'Unpaid'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('special_requirements', models.TextField(blank=True)),
                ('group_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.groupbooking')),
                ('room_preference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('is_deposit', models.BooleanField(default=False)),
                ('group_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.groupbooking')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.groupmember')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBookingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rooms', models.IntegerField()),
                ('total_members', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_stay_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.groupbooking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('additional_services', models.JSONField(default=dict)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('terms', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('included_room_types', models.ManyToManyField(to='hotel.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.cancellationpolicy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='group_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_leader_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_hotel', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookingpackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_room_type', to='hotel.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room_type', 'check_in', 'check_out')},
            },
        ),
        migrations.CreateModel(
            name='GroupRoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('group_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.groupbooking')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.groupmember')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'unique_together': {('room', 'check_in_date')},
            },
        ),
    ]
